const STORAGE={students:"enp_students_v1",attendance:"enp_attendance_v1",theme:"enp_theme_v1",pin:"enp_pin_v1",profile:"enp_profile_v1",receipts:"enp_receipts_v1"};
const CLASS_DAYS=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
const COURSES=["ICTT","Graphic Design","School ICT Book Grade 6-11","Kid Course"];
const today=()=>new Date().toISOString().slice(0,10);
const money=n=>"Rs. "+Number(n||0).toLocaleString("en-US");
const classDayForDate=date=>date?["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][new Date(`${date}T00:00:00`).getDay()]:"";
const initials=n=>n.split(" ").filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase();
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const seed=[
  ["ENP-001","Nethmi Perera","077 234 1123","071 908 4532","Computer Basics","Monday","2026-01-08",24000,24000],
  ["ENP-002","Kasun Silva","071 832 6765","077 456 2311","MS Office Professional","Saturday","2026-01-12",32000,20000],
  ["ENP-003","Sajini Fernando","076 444 1980","071 334 9201","Graphic Design","Tuesday","2026-02-03",45000,45000],
  ["ENP-004","Tharindu Madushan","075 802 6214","077 932 1104","Computer Basics","Saturday","2026-02-11",24000,12000],
  ["ENP-005","Dinithi Sewwandi","077 529 8802","070 118 9081","Web Development","Wednesday","2026-02-18",60000,40000],
  ["ENP-006","Ravindu Lakshan","070 722 5019","077 200 4567","MS Office Professional","Saturday","2026-03-01",32000,0],
  ["ENP-007","Kavindi Jayasinghe","076 101 8809","071 898 4432","Graphic Design","Saturday","2026-03-17",45000,30000],
  ["ENP-008","Sahan Mihiranga","071 232 0405","075 456 0098","Web Development","Thursday","2026-04-05",60000,60000],
  ["ENP-009","Piumi Hansika","075 221 0876","077 674 2310","Computer Basics","Saturday","2026-04-22",24000,8000],
  ["ENP-010","Isuru Dhananjaya","077 890 5503","070 342 0081","MS Office Professional","Friday","2026-05-08",32000,32000],
  ["ENP-011","Chamodi Rashmika","071 670 3112","076 200 4578","Graphic Design","Saturday","2026-05-19",45000,15000],
  ["ENP-012","Dulanjana Bandara","076 320 9011","077 543 9087","Computer Basics","Monday","2026-06-02",24000,12000]
].map(([id,name,phone,guardian,course,group,joined,fee,paid])=>({id,name,phone,guardian,course,group,joined,fee,paid}));
let students=JSON.parse(localStorage.getItem(STORAGE.students)||"null")||seed;
let attendance=JSON.parse(localStorage.getItem(STORAGE.attendance)||"{}");
let profile=JSON.parse(localStorage.getItem(STORAGE.profile)||"null")||{name:"Administrator",role:"Center Admin",email:"",phone:""};
let loginPin=localStorage.getItem(STORAGE.pin)||"1234";
let receipts=JSON.parse(localStorage.getItem(STORAGE.receipts)||"[]");
students=students.map(s=>({...s,group:s.group==="Weekday"?CLASS_DAYS[(Number(s.id.split("-")[1])||1)%5]:s.group}));
const courseMigration={"Computer Basics":"ICTT","MS Office Professional":"ICTT","Web Development":"ICTT","Graphic Design":"Graphic Design","School ICT Book Grade 6-11":"School ICT Book Grade 6-11","Kid Course":"Kid Course"};
students=students.map((s,i)=>({...s,course:courseMigration[s.course]||COURSES[i%COURSES.length]}));
students=students.map(s=>({...s,group:s.course==="Kid Course"?"Flexible":s.group}));
let draftAttendance={};
let lastAttendanceReport=null;
let lastReceipt=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function setTheme(theme){const dark=theme==="dark";document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem(STORAGE.theme,dark?"dark":"light");if($("#themeIcon"))$("#themeIcon").textContent=dark?"☀":"☾";if($("#themeToggle")){$("#themeToggle").setAttribute("aria-label",dark?"Switch to light mode":"Switch to dark mode");$("#themeToggle").title=dark?"Switch to light mode":"Switch to dark mode"}document.querySelector('meta[name="theme-color"]').content=dark?"#09182b":"#124e96"}
function profileLetters(){return initials(profile.name||"Administrator")}
function renderProfile(){const letters=profileLetters();$("#profileInitials").textContent=letters;$("#menuProfileInitials").textContent=letters;$("#profileModalInitials").textContent=letters;$("#menuProfileName").textContent=profile.name;$("#menuProfileRole").textContent=profile.role;$("#profileHeroName").textContent=profile.name}
function lockSystem(){sessionStorage.removeItem("enp_unlocked");document.body.classList.add("system-locked");$("#profileMenu").classList.remove("open");$("#loginPin").value="";$("#loginError").textContent="";$("#loginScreen").classList.remove("hidden");setTimeout(()=>$("#loginPin").focus(),100)}
function unlockSystem(){sessionStorage.setItem("enp_unlocked","1");document.body.classList.remove("system-locked");$("#loginScreen").classList.add("hidden")}
function openProfile(){renderProfile();$("#profileName").value=profile.name;$("#profileRole").value=profile.role;$("#profileEmail").value=profile.email;$("#profilePhone").value=profile.phone;$("#pinForm").reset();$("#profileMenu").classList.remove("open");$("#profileModal").classList.add("open")}
const persist=()=>{localStorage.setItem(STORAGE.students,JSON.stringify(students));localStorage.setItem(STORAGE.attendance,JSON.stringify(attendance));localStorage.setItem(STORAGE.receipts,JSON.stringify(receipts))};
const paymentStatus=s=>s.paid>=s.fee?"Paid":"Pending";
const badge=(text,type=text)=>`<span class="badge ${type.toLowerCase()}">${esc(text)}</span>`;
const studentCell=s=>`<div class="student-cell"><span class="avatar">${initials(s.name)}</span><div class="person"><strong>${esc(s.name)}</strong><small>${esc(s.id)}</small></div></div>`;
const empty=(cols,text="No records found")=>`<tr><td colspan="${cols}" class="empty">${text}</td></tr>`;
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
function whatsappNumber(phone){let n=String(phone||"").replace(/\D/g,"");if(n.startsWith("0"))n=`94${n.slice(1)}`;return n}
function pdfEscape(text){return String(text).replace(/\\/g,"\\\\").replace(/\(/g,"\\(").replace(/\)/g,"\\)").replace(/[^\x20-\x7E]/g,"")}
function receiptPDF(r){
  const blue="0.075 0.247 0.486",light="0.945 0.969 1",ink="0.08 0.14 0.23",muted="0.42 0.50 0.60",green="0.08 0.55 0.34",gold="0.96 0.70 0.10";
  let s="";
  const fill=c=>{s+=`${c} rg\n`},stroke=c=>{s+=`${c} RG\n`},rect=(x,y,w,h,c)=>{fill(c);s+=`${x} ${y} ${w} ${h} re f\n`},border=(x,y,w,h,c=blue,lineWidth=1)=>{stroke(c);s+=`${lineWidth} w ${x} ${y} ${w} ${h} re S\n`},line=(x1,y1,x2,y2,c,w=1)=>{stroke(c);s+=`${w} w ${x1} ${y1} m ${x2} ${y2} l S\n`},text=(v,x,y,size=10,bold=false,c=ink)=>{fill(c);s+=`BT /${bold?"F2":"F1"} ${size} Tf ${x} ${y} Td (${pdfEscape(v)}) Tj ET\n`};
  const field=(label,value,x,y)=>{text(label.toUpperCase(),x,y,7,true,muted);text(value,x,y-16,10,true,ink)};

  rect(0,0,595,842,"1 1 1");border(18,18,559,806,blue,2);border(24,24,547,794,"0.72 0.82 0.93",0.7);rect(0,702,595,140,blue);rect(0,696,595,6,gold);
  rect(45,744,64,64,"1 1 1");border(45,744,64,64,"0.79 0.89 1",1.5);rect(53,752,48,48,blue);
  line(77,758,77,793,"1 1 1",2);line(59,787,77,792,"1 1 1",2);line(95,787,77,792,"1 1 1",2);
  line(59,778,70,778,"0.79 0.89 1",2);line(84,778,95,778,"0.79 0.89 1",2);line(59,769,70,769,"0.79 0.89 1",2);line(84,769,95,769,"0.79 0.89 1",2);
  fill(gold);s+="86 750 m 86 755 82 759 77 759 c 72 759 68 755 68 750 c 68 745 72 741 77 741 c 82 741 86 745 86 750 c f\n";line(73,750,76,747,blue,2);line(76,747,82,754,blue,2);
  text("E nena Piyasa",128,782,22,true,"1 1 1");text("COMPUTER TECHNOLOGY CENTER",128,762,8,true,"0.79 0.89 1");
  text("PAYMENT RECEIPT",393,782,14,true,"1 1 1");text("Official payment confirmation",393,763,8,false,"0.79 0.89 1");

  rect(45,638,505,42,light);border(45,638,505,42,"0.65 0.76 0.88",1);line(297,638,297,680,"0.75 0.82 0.90",0.7);field("Receipt Number",r.number,60,665);field("Issued Date & Time",r.dateText,330,665);
  text("STUDENT INFORMATION",45,608,9,true,blue);line(45,600,550,600,"0.86 0.90 0.95");
  border(45,502,505,88,"0.75 0.82 0.90",1);line(297,502,297,590,"0.82 0.87 0.93",0.7);line(45,546,550,546,"0.82 0.87 0.93",0.7);
  field("Received From",r.student.name,60,578);field("Student ID",r.student.id,330,578);
  field("Course",r.student.course,60,526);field("WhatsApp Number",r.student.phone,330,526);

  rect(45,416,505,80,blue);border(45,416,505,80,gold,2);text("PAYMENT RECEIVED",65,471,8,true,"0.79 0.89 1");text(money(r.payment),65,438,28,true,"1 1 1");
  rect(425,435,105,38,paymentStatus(r.student)==="Paid"?green:gold);text(paymentStatus(r.student).toUpperCase(),451,449,11,true,"1 1 1");

  text("PAYMENT SUMMARY",45,382,9,true,blue);line(45,374,550,374,"0.86 0.90 0.95");
  rect(45,276,505,78,light);border(45,276,505,78,"0.65 0.76 0.88",1);line(200,276,200,354,"0.75 0.82 0.90",0.7);line(370,276,370,354,"0.75 0.82 0.90",0.7);field("Total Course Fee",money(r.student.fee),65,334);field("Total Paid To Date",money(r.student.paid),220,334);field("Outstanding Balance",money(r.balance),390,334);

  text("Thank you for your payment.",45,236,13,true,blue);text("Please keep this receipt for your records. This is a computer-generated receipt.",45,216,8,false,muted);
  rect(45,126,505,46,light);border(45,126,505,46,"0.75 0.82 0.90",0.8);text("VERIFIED DIGITAL RECEIPT",65,151,8,true,blue);text("Receipt authenticity is confirmed by its unique receipt number and system record.",65,136,8,false,muted);
  rect(0,0,595,62,blue);text("E nena Piyasa Computer Technology Center",45,36,8,true,"1 1 1");text("Designed & Developed by Blank-X-Innovation",355,36,7,false,"0.79 0.89 1");

  const objects=[null,"<< /Type /Catalog /Pages 2 0 R >>","<< /Type /Pages /Kids [3 0 R] /Count 1 >>","<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> /Contents 4 0 R >>",`<< /Length ${s.length} >>\nstream\n${s}endstream`,"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>","<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>"];
  let pdf="%PDF-1.4\n",offsets=[0];for(let i=1;i<objects.length;i++){offsets[i]=pdf.length;pdf+=`${i} 0 obj\n${objects[i]}\nendobj\n`}const xref=pdf.length;pdf+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)pdf+=`${String(offsets[i]).padStart(10,"0")} 00000 n \n`;pdf+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Blob([pdf],{type:"application/pdf"})
}
function receiptFile(){return new File([receiptPDF(lastReceipt)],`${lastReceipt.number}.pdf`,{type:"application/pdf"})}
function downloadReceiptPDF(){if(!lastReceipt)return;const a=document.createElement("a");a.href=URL.createObjectURL(receiptPDF(lastReceipt));a.download=`${lastReceipt.number}.pdf`;a.click();URL.revokeObjectURL(a.href)}
function openReceipt(receipt){lastReceipt=JSON.parse(JSON.stringify(receipt));const student=lastReceipt.student,payment=lastReceipt.payment,balance=lastReceipt.balance,number=lastReceipt.number,dateText=lastReceipt.dateText;$("#receiptNumber").textContent=number;$("#receiptDate").textContent=dateText;$("#receiptStudent").textContent=student.name;$("#receiptStudentId").textContent=student.id;$("#receiptCourse").textContent=student.course;$("#receiptPhone").textContent=student.phone;$("#receiptPayment").textContent=money(payment);$("#receiptFee").textContent=money(student.fee);$("#receiptTotalPaid").textContent=money(student.paid);$("#receiptBalance").textContent=money(balance);$("#receiptStatus").textContent=paymentStatus(student);$("#receiptModal").classList.add("open")}
function showReceipt(student,payment){const now=new Date(),number=`ENP-${now.getFullYear()}${String(now.getMonth()+1).padStart(2,"0")}${String(now.getDate()).padStart(2,"0")}-${String(now.getTime()).slice(-6)}`,dateText=new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(now),balance=Math.max(0,student.fee-student.paid),receipt={number,dateText,createdAt:now.toISOString(),student:{...student},payment,balance};receipts.unshift(receipt);persist();openReceipt(receipt)}
function go(view){$$(".view").forEach(v=>v.classList.remove("active"));$(`#${view}View`).classList.add("active");$$(".nav-item").forEach(n=>n.classList.toggle("active",n.dataset.view===view));$("#pageTitle").textContent={dashboard:"Dashboard",students:"Student Management",attendance:"Day Register",kidAttendance:"Kid Course Register",history:"Register History",payments:"Payment Management",receiptLookup:"Receipt Lookup"}[view];$("#sidebar").classList.remove("open");renderAll()}
function renderDashboard(){
  const fees=students.reduce((a,s)=>a+s.fee,0),paid=students.reduce((a,s)=>a+s.paid,0),marks=attendance[today()]||{},present=Object.values(marks).filter(x=>x==="present").length;
  $("#statStudents").textContent=students.length;$("#statActive").textContent=`${students.length} active registrations`;$("#statPresent").textContent=present;$("#statAttendanceRate").textContent=`${students.length?Math.round(present/students.length*100):0}% attendance rate`;$("#statCollected").textContent=money(paid);$("#statOutstanding").textContent=`${money(fees-paid)} outstanding`;$("#statGroups").textContent=new Set(students.filter(s=>s.course!=="Kid Course").map(s=>s.group)).size;
  $("#distribution").innerHTML=CLASS_DAYS.map(g=>{const n=students.filter(s=>s.group===g).length,p=students.length?Math.round(n/students.length*100):0;return`<div class="dist-row"><span>${g}</span><div class="bar"><i style="width:${p}%"></i></div><strong>${n}</strong></div>`}).join("");
  const due=[...students].filter(s=>s.paid<s.fee).sort((a,b)=>(b.fee-b.paid)-(a.fee-a.paid)).slice(0,4);$("#paymentFollowup").innerHTML=due.length?due.map(s=>`<div class="followup"><span class="avatar">${initials(s.name)}</span><div class="person"><strong>${esc(s.name)}</strong><small>${esc(s.course)}</small></div><span class="amount">${money(s.fee-s.paid)} due</span></div>`).join(""):`<div class="empty">All payments are complete</div>`;
  $("#recentStudents").innerHTML=[...students].sort((a,b)=>b.joined.localeCompare(a.joined)).slice(0,5).map(s=>`<tr><td>${studentCell(s)}</td><td>${esc(s.phone)}</td><td>${esc(s.course)}</td><td>${badge(s.group,"day")}</td><td>${badge(paymentStatus(s))}</td></tr>`).join("")||empty(5);
  COURSES.forEach(course=>{const el=document.querySelector(`[data-course-count="${course}"]`);if(el)el.textContent=students.filter(s=>s.course===course).length});
}
function filteredStudents(){const q=$("#studentSearch").value.toLowerCase(),c=$("#courseFilter").value,g=$("#groupFilter").value,p=$("#statusFilter").value;return students.filter(s=>(c==="all"||s.course===c)&&(g==="all"||s.group===g)&&(p==="all"||paymentStatus(s)===p)&&[s.name,s.id,s.phone,s.course].some(v=>v.toLowerCase().includes(q)))}
function renderStudents(){const list=filteredStudents();$("#studentCountLabel").textContent=`${list.length} student${list.length===1?"":"s"}`;$("#studentsTable").innerHTML=list.map(s=>`<tr><td>${studentCell(s)}</td><td>${esc(s.phone)}<br><small>${esc(s.guardian||"No guardian phone")}</small></td><td>${esc(s.course)}</td><td>${badge(s.group,"day")}</td><td><strong>${money(s.paid)}</strong><br><small>of ${money(s.fee)}</small></td><td>${badge(paymentStatus(s))}</td><td><div class="action-row"><button class="mini-button" data-edit="${s.id}">Edit</button><button class="mini-button danger" data-delete="${s.id}">Remove</button></div></td></tr>`).join("")||empty(7)}
function renderAttendance(){
  const date=$("#attendanceDate").value,day=classDayForDate(date),q=$("#attendanceSearch").value.toLowerCase();if(!draftAttendance[date])draftAttendance[date]={...(attendance[date]||{})};$("#selectedClassDay").textContent=day==="Sunday"?"Sunday - No Classes":day;
  const registerStudents=students.filter(s=>s.course!=="Kid Course"&&s.group===day),list=registerStudents.filter(s=>[s.name,s.id,s.course].some(v=>v.toLowerCase().includes(q))),marks=draftAttendance[date];
  $("#attendanceTable").innerHTML=list.map(s=>`<tr><td>${studentCell(s)}</td><td>${esc(s.course)}</td><td>${badge(s.group,"day")}</td><td class="center"><button class="attendance-toggle present ${marks[s.id]==="present"?"active":""}" data-mark="${s.id}" data-value="present">✓</button></td><td class="center"><button class="attendance-toggle absent ${marks[s.id]==="absent"?"active":""}" data-mark="${s.id}" data-value="absent">×</button></td></tr>`).join("")||empty(5);
  if(!list.length)$("#attendanceTable").innerHTML=empty(5,day==="Sunday"?"No regular classes are scheduled on Sunday.":`No students assigned to ${day}`);
  const vals=registerStudents.map(s=>marks[s.id]),present=vals.filter(x=>x==="present").length,absent=vals.filter(x=>x==="absent").length;$("#expectedCount").textContent=registerStudents.length;$("#presentCount").textContent=present;$("#absentCount").textContent=absent;$("#attendancePercent").textContent=`${registerStudents.length?Math.round(present/registerStudents.length*100):0}%`;
}
function kidRecordKey(date){return`kid:${date}`}
function renderKidAttendance(){const date=$("#kidAttendanceDate").value,key=kidRecordKey(date),q=$("#kidAttendanceSearch").value.toLowerCase();if(!draftAttendance[key])draftAttendance[key]={...(attendance[key]||{})};if(!draftAttendance[key].__kids)draftAttendance[key].__kids=[];const marks=draftAttendance[key],selected=marks.__kids,kids=students.filter(s=>s.course==="Kid Course"),included=kids.filter(s=>selected.includes(s.id)),list=included.filter(s=>[s.name,s.id,s.phone].some(v=>v.toLowerCase().includes(q)));$("#kidSelector").innerHTML=kids.length?kids.map(s=>`<label class="kid-option"><input type="checkbox" data-kid="${s.id}" ${selected.includes(s.id)?"checked":""}><span class="avatar">${initials(s.name)}</span><span><strong>${esc(s.name)}</strong><small>${esc(s.id)}</small></span></label>`).join(""):`<span class="muted">No Kid Course students registered.</span>`;$("#kidAttendanceTable").innerHTML=list.map(s=>`<tr><td>${studentCell(s)}</td><td>${esc(s.course)}</td><td>${badge(s.group,"day")}</td><td class="center"><button class="attendance-toggle present ${marks[s.id]==="present"?"active":""}" data-kid-mark="${s.id}" data-value="present">✓</button></td><td class="center"><button class="attendance-toggle absent ${marks[s.id]==="absent"?"active":""}" data-kid-mark="${s.id}" data-value="absent">×</button></td></tr>`).join("")||empty(5,"Select Kid Course students above to begin the register");const vals=included.map(s=>marks[s.id]),present=vals.filter(x=>x==="present").length,absent=vals.filter(x=>x==="absent").length;$("#kidExpectedCount").textContent=included.length;$("#kidPresentCount").textContent=present;$("#kidAbsentCount").textContent=absent;$("#kidAttendancePercent").textContent=`${included.length?Math.round(present/included.length*100):0}%`}
function resultStudent(s){return`<div class="result-person">${studentCell(s)}<div class="result-details"><span>${esc(s.course)}</span><span>${esc(s.phone)}</span><span>${esc(s.guardian||"No guardian phone")}</span></div></div>`}
function showAttendanceResult(date){const kidRegister=date.startsWith("kid:"),actualDate=kidRegister?date.slice(4):date,day=kidRegister?"Kid Course":classDayForDate(actualDate),marks=attendance[date]||{},kidIds=marks.__kids||[],assigned=kidRegister?students.filter(s=>s.course==="Kid Course"&&kidIds.includes(s.id)):students.filter(s=>s.course!=="Kid Course"&&s.group===day),present=assigned.filter(s=>marks[s.id]==="present"),absent=assigned.filter(s=>marks[s.id]==="absent"),percent=assigned.length?Math.round(present.length/assigned.length*100):0;lastAttendanceReport={date,day,assigned,present,absent};$("#resultDay").textContent=kidRegister?"Kid Course Register":`${day} Register`;$("#resultDate").textContent=new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"long",year:"numeric"}).format(new Date(`${actualDate}T00:00:00`));$("#resultExpected").textContent=assigned.length;$("#resultPresent").textContent=present.length;$("#resultAbsent").textContent=absent.length;$("#resultPercent").textContent=`${percent}%`;$("#presentResultCount").textContent=present.length;$("#absentResultCount").textContent=absent.length;$("#presentResultList").innerHTML=present.map(resultStudent).join("")||`<div class="result-empty">No present students</div>`;$("#absentResultList").innerHTML=absent.map(resultStudent).join("")||`<div class="result-empty">No absent students</div>`;$("#attendanceResultModal").classList.add("open")}
function filteredPayments(){const q=$("#paymentSearch").value.toLowerCase(),p=$("#paymentFilter").value;return students.filter(s=>(p==="all"||paymentStatus(s)===p)&&[s.name,s.id,s.course].some(v=>v.toLowerCase().includes(q)))}
function renderPayments(){const fee=students.reduce((a,s)=>a+s.fee,0),paid=students.reduce((a,s)=>a+s.paid,0);$("#totalFees").textContent=money(fee);$("#totalCollected").textContent=money(paid);$("#totalOutstanding").textContent=money(fee-paid);const list=filteredPayments();$("#paymentsTable").innerHTML=list.map(s=>{const pct=s.fee?Math.min(100,Math.round(s.paid/s.fee*100)):100;return`<tr><td>${studentCell(s)}</td><td>${esc(s.course)}</td><td>${money(s.fee)}</td><td><strong>${money(s.paid)}</strong></td><td class="amount">${money(Math.max(0,s.fee-s.paid))}</td><td><div class="payment-progress"><div class="progress"><i style="width:${pct}%"></i></div><small>${pct}% paid</small></div></td><td><button class="mini-button" data-pay="${s.id}" ${s.paid>=s.fee?"disabled":""}>Add payment</button></td></tr>`}).join("")||empty(7)}
function historyReport(date){const kidRegister=date.startsWith("kid:"),actualDate=kidRegister?date.slice(4):date,marks=attendance[date]||{},day=kidRegister?"Kid Course":classDayForDate(actualDate),kidIds=marks.__kids||[],assigned=kidRegister?students.filter(s=>s.course==="Kid Course"&&kidIds.includes(s.id)):students.filter(s=>s.course!=="Kid Course"&&s.group===day),present=assigned.filter(s=>marks[s.id]==="present"),absent=assigned.filter(s=>marks[s.id]==="absent");return{date,actualDate,day,assigned,present,absent,courses:[...new Set(assigned.map(s=>s.course))]}}
function renderHistory(){const reports=Object.keys(attendance).sort((a,b)=>b.localeCompare(a)).map(historyReport),q=$("#historySearch").value.toLowerCase(),filtered=reports.filter(r=>[r.actualDate,r.day,...r.courses].some(v=>v.toLowerCase().includes(q)));$("#historyTotal").textContent=reports.length;$("#historyPresent").textContent=reports.reduce((n,r)=>n+r.present.length,0);$("#historyAbsent").textContent=reports.reduce((n,r)=>n+r.absent.length,0);$("#historyGrid").innerHTML=filtered.length?filtered.map(r=>{const pct=r.assigned.length?Math.round(r.present.length/r.assigned.length*100):0;return`<article class="history-card"><div class="history-date"><span>${r.day.slice(0,3)}</span><div><strong>${new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${r.actualDate}T00:00:00`))}</strong><small>${r.day} register</small></div></div><div class="history-courses">${r.courses.map(c=>badge(c,"day")).join("")||badge("No course","day")}</div><div class="history-stats"><span>Expected<strong>${r.assigned.length}</strong></span><span>Present<strong>${r.present.length}</strong></span><span>Absent<strong>${r.absent.length}</strong></span><span>Rate<strong>${pct}%</strong></span></div><button class="button secondary" data-history-date="${r.date}">View Complete Report</button></article>`}).join(""):`<div class="panel empty">No saved registers found</div>`}
function renderAll(){renderDashboard();renderStudents();renderAttendance();renderKidAttendance();renderPayments();renderHistory()}
function syncCourseDay(){const kid=$("#studentCourse").value==="Kid Course";$("#studentGroup").value=kid?"Flexible":($("#studentGroup").value==="Flexible"?"Monday":$("#studentGroup").value);$("#studentGroup").disabled=kid;$("#classDayHelp").textContent=kid?"Kid Course attendance day is selected manually in Day Register.":"Required for regular courses."}
function openStudent(id){$("#studentForm").reset();$("#studentId").value=id||"";$("#modalTitle").textContent=id?"Edit Student":"Add New Student";const s=students.find(x=>x.id===id);if(s){$("#studentName").value=s.name;$("#studentPhone").value=s.phone;$("#guardianPhone").value=s.guardian;$("#studentCourse").value=s.course;$("#studentGroup").value=s.group;$("#joinedDate").value=s.joined;$("#courseFee").value=s.fee;$("#amountPaid").value=s.paid}else{$("#joinedDate").value=today();$("#courseFee").value=24000;$("#amountPaid").value=0}syncCourseDay();$("#studentModal").classList.add("open")}
function closeModals(){$$(".modal-backdrop").forEach(m=>m.classList.remove("open"))}
function nextId(){const max=Math.max(0,...students.map(s=>Number(s.id.split("-")[1])||0));return`ENP-${String(max+1).padStart(3,"0")}`}
$("#studentForm").addEventListener("submit",e=>{e.preventDefault();const id=$("#studentId").value||nextId(),course=$("#studentCourse").value,data={id,name:$("#studentName").value.trim(),phone:$("#studentPhone").value.trim(),guardian:$("#guardianPhone").value.trim(),course,group:course==="Kid Course"?"Flexible":$("#studentGroup").value,joined:$("#joinedDate").value,fee:Number($("#courseFee").value),paid:Number($("#amountPaid").value)};if(data.paid>data.fee)return toast("Paid amount cannot exceed the course fee");const i=students.findIndex(s=>s.id===id);i>=0?students[i]=data:students.push(data);persist();closeModals();renderAll();toast(i>=0?"Student details updated":"Student registered successfully")});
document.addEventListener("click",e=>{const t=e.target;if(t.dataset.go)go(t.dataset.go);if(t.dataset.close)closeModals();if(t.dataset.historyDate)showAttendanceResult(t.dataset.historyDate);if(t.dataset.edit)openStudent(t.dataset.edit);if(t.dataset.delete){const s=students.find(x=>x.id===t.dataset.delete);if(s&&confirm(`Remove ${s.name} from the system?`)){students=students.filter(x=>x.id!==s.id);persist();renderAll();toast("Student removed")}}if(t.dataset.mark){const d=$("#attendanceDate").value;draftAttendance[d][t.dataset.mark]=t.dataset.value;renderAttendance()}if(t.dataset.kidMark){const key=kidRecordKey($("#kidAttendanceDate").value);draftAttendance[key][t.dataset.kidMark]=t.dataset.value;renderKidAttendance()}if(t.dataset.pay){const s=students.find(x=>x.id===t.dataset.pay);$("#paymentStudentId").value=s.id;$("#paymentPerson").innerHTML=`${studentCell(s)}<p class="muted">Outstanding: <strong>${money(s.fee-s.paid)}</strong></p>`;$("#newPayment").value="";$("#newPayment").max=s.fee-s.paid;$("#paymentModal").classList.add("open")}});
$$(".course-nav-item").forEach(button=>button.onclick=()=>{$("#courseFilter").value=button.dataset.courseNav;go("students");$$(".course-nav-item").forEach(x=>x.classList.toggle("active",x===button));$("#pageTitle").textContent=button.dataset.courseNav});
$("#loginForm").addEventListener("submit",e=>{e.preventDefault();if($("#loginPin").value===loginPin){unlockSystem();$("#loginError").textContent="";toast(`Welcome, ${profile.name}`)}else{$("#loginError").textContent="Incorrect PIN. Please try again.";$("#loginPin").select()}});
$("#profileForm").addEventListener("submit",e=>{e.preventDefault();profile={name:$("#profileName").value.trim(),role:$("#profileRole").value.trim(),email:$("#profileEmail").value.trim(),phone:$("#profilePhone").value.trim()};localStorage.setItem(STORAGE.profile,JSON.stringify(profile));renderProfile();toast("Profile updated successfully")});
$("#pinForm").addEventListener("submit",e=>{e.preventDefault();const current=$("#currentPin").value,newValue=$("#newPin").value,confirmValue=$("#confirmPin").value;if(current!==loginPin)return toast("Current PIN is incorrect");if(!/^[0-9]{4,8}$/.test(newValue))return toast("PIN must contain 4 to 8 numbers");if(newValue!==confirmValue)return toast("New PIN confirmation does not match");loginPin=newValue;localStorage.setItem(STORAGE.pin,loginPin);$("#loginHint").hidden=true;$("#pinForm").reset();toast("Login PIN updated successfully")});
$("#paymentForm").addEventListener("submit",e=>{e.preventDefault();const s=students.find(x=>x.id===$("#paymentStudentId").value),n=Number($("#newPayment").value);if(n>s.fee-s.paid)return toast("Payment exceeds the outstanding balance");s.paid+=n;persist();closeModals();renderAll();showReceipt(s,n);toast("Payment recorded and receipt generated")});
function exportCSV(name,rows){const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function downloadJSON(name,data){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$("#exportStudents").onclick=()=>exportCSV("enp-students.csv",[["ID","Name","Phone","Guardian","Course","Group","Joined","Fee","Paid","Status"],...filteredStudents().map(s=>[s.id,s.name,s.phone,s.guardian,s.course,s.group,s.joined,s.fee,s.paid,paymentStatus(s)])]);
$("#exportPayments").onclick=()=>exportCSV("enp-payments.csv",[["ID","Name","Course","Fee","Paid","Outstanding","Status"],...filteredPayments().map(s=>[s.id,s.name,s.course,s.fee,s.paid,s.fee-s.paid,paymentStatus(s)])]);
$("#exportAttendance").onclick=()=>{if(!lastAttendanceReport)return;const r=lastAttendanceReport;exportCSV(`enp-attendance-${r.date}.csv`,[["Date","Day","Status","Student ID","Student Name","Course","Phone","Guardian Phone"],...r.assigned.map(s=>[r.date,r.day,attendance[r.date][s.id],s.id,s.name,s.course,s.phone,s.guardian])])};
$("#downloadAttendanceBackup").onclick=()=>downloadJSON(`enp-attendance-backup-${today()}.json`,{system:"E nena Piyasa Management System",exportedAt:new Date().toISOString(),students,attendance});
$("#historyBackup").onclick=$("#downloadAttendanceBackup").onclick;
$("#printReceipt").onclick=downloadReceiptPDF;
$("#whatsappReceipt").onclick=async()=>{if(!lastReceipt)return;const file=receiptFile();if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({title:"E nena Piyasa Payment Receipt",text:`Payment receipt for ${lastReceipt.student.name}`,files:[file]});toast("PDF receipt shared successfully")}catch(e){if(e.name!=="AbortError")toast("Unable to share PDF receipt")}}else{downloadReceiptPDF();const number=whatsappNumber(lastReceipt.student.phone);if(number)window.open(`https://wa.me/${number}`,"_blank");toast("PDF downloaded. Attach it in WhatsApp.")}};
$("#saveAttendance").onclick=()=>{const date=$("#attendanceDate").value,day=classDayForDate(date),marks=draftAttendance[date]||{},assigned=students.filter(s=>s.course!=="Kid Course"&&s.group===day),unmarked=assigned.filter(s=>!marks[s.id]);if(!assigned.length)return toast("No regular course students assigned to this date");if(unmarked.length)return toast(`Mark Present or Absent for all ${unmarked.length} remaining students`);attendance[date]={...marks};persist();renderAll();showAttendanceResult(date);toast("Day register completed and saved")};
$("#saveKidAttendance").onclick=()=>{const date=$("#kidAttendanceDate").value,key=kidRecordKey(date),marks=draftAttendance[key]||{},kidIds=marks.__kids||[],assigned=students.filter(s=>s.course==="Kid Course"&&kidIds.includes(s.id)),unmarked=assigned.filter(s=>!marks[s.id]);if(!assigned.length)return toast("Select Kid Course students for this register");if(unmarked.length)return toast(`Mark Present or Absent for all ${unmarked.length} selected kids`);attendance[key]={...marks};persist();renderAll();showAttendanceResult(key);toast("Kid Course register completed and saved")};
$("#markAllPresent").onclick=()=>{const d=$("#attendanceDate").value,day=classDayForDate(d);students.filter(s=>s.course!=="Kid Course"&&s.group===day).forEach(s=>draftAttendance[d][s.id]="present");renderAttendance()};
$("#markAllKidsPresent").onclick=()=>{const key=kidRecordKey($("#kidAttendanceDate").value),ids=draftAttendance[key].__kids||[];ids.forEach(id=>draftAttendance[key][id]="present");renderKidAttendance()};
$("#clearAttendance").onclick=()=>{draftAttendance[$("#attendanceDate").value]={};renderAttendance()};
$("#clearKidAttendance").onclick=()=>{draftAttendance[kidRecordKey($("#kidAttendanceDate").value)]={__kids:[]};renderKidAttendance()};
$("#addStudent").onclick=()=>openStudent();$("#quickAdd").onclick=()=>openStudent();$("#menuButton").onclick=()=>$("#sidebar").classList.toggle("open");
$("#themeToggle").onclick=()=>setTheme(document.documentElement.dataset.theme==="dark"?"light":"dark");
$("#studentCourse").addEventListener("change",syncCourseDay);$("#kidSelector").addEventListener("change",e=>{if(!e.target.dataset.kid)return;const key=kidRecordKey($("#kidAttendanceDate").value),list=draftAttendance[key].__kids||[];if(e.target.checked&&!list.includes(e.target.dataset.kid))list.push(e.target.dataset.kid);if(!e.target.checked){draftAttendance[key][e.target.dataset.kid]=undefined;list.splice(list.indexOf(e.target.dataset.kid),1)}draftAttendance[key].__kids=list;renderKidAttendance()});
$("#profileButton").onclick=e=>{e.stopPropagation();$("#profileMenu").classList.toggle("open")};$("#openProfile").onclick=openProfile;$("#lockSystem").onclick=lockSystem;$("#logoutSystem").onclick=lockSystem;document.addEventListener("click",e=>{if(!e.target.closest(".profile-wrap"))$("#profileMenu").classList.remove("open")});
$$(".nav-item").forEach(n=>n.onclick=()=>{$$(".course-nav-item").forEach(x=>x.classList.remove("active"));if(n.dataset.view==="students")$("#courseFilter").value="all";go(n.dataset.view)});["studentSearch","courseFilter","groupFilter","statusFilter"].forEach(id=>$(`#${id}`).addEventListener("input",()=>{$$(".course-nav-item").forEach(x=>x.classList.toggle("active",$("#courseFilter").value===x.dataset.courseNav));renderStudents()}));["attendanceDate","attendanceSearch"].forEach(id=>$(`#${id}`).addEventListener("input",renderAttendance));["kidAttendanceDate","kidAttendanceSearch"].forEach(id=>$(`#${id}`).addEventListener("input",renderKidAttendance));["paymentSearch","paymentFilter"].forEach(id=>$(`#${id}`).addEventListener("input",renderPayments));$("#historySearch").addEventListener("input",renderHistory);
setTheme(localStorage.getItem(STORAGE.theme)||"light");renderProfile();$("#loginHint").hidden=Boolean(localStorage.getItem(STORAGE.pin));if(sessionStorage.getItem("enp_unlocked")==="1")unlockSystem();else lockSystem();$("#todayLabel").textContent=new Intl.DateTimeFormat("en-GB",{weekday:"short",day:"2-digit",month:"short",year:"numeric"}).format(new Date());$("#attendanceDate").value=today();$("#kidAttendanceDate").value=today();renderAll();
